
public class TEXTO_AULA {
   
	
	
	/* REGRAS DOS CONSTRUTORES;
	 * 
	 * 1- TODA CLASSE POSSUI UM CONSTRUTOR.
	 * 2- O CONSTRUTOR É UM MÉTODO COM O MESMO NOME DA CLASSE.
	 * 3- SE NENHUM CONSTRUTOR FOR ENCONTRADO NA CLASSE, O COMPILADOR INCLUIR UM CONSTRUTOR PADRÃO
	 * 		=(ATRIBUIR VALORES DEFAULT PARA OS ATRIBUTOS DA CLASSE).
    * 4- SE COLOCARMOS PELO MENOS UM CONSTRUTOR NA CLASSE, ESTE SERÁ USADO, E O COMPILADOR NÃO
    * INTERFERE MAIS.
    * 
    * 5- O CONSTRUTOR É UM MÉTODO SEM VALOR DE RETORNO DEFINIDO.
    */
	
}
